ALTER TABLE public.guide_content
    ADD COLUMN IF NOT EXISTS deleted_at timestamp(6) with time zone,
    ADD COLUMN IF NOT EXISTS deleted_by_user_id uuid,
    ADD COLUMN IF NOT EXISTS deleted_reason character varying(255),
    ADD COLUMN IF NOT EXISTS like_count bigint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS comment_count bigint NOT NULL DEFAULT 0;

CREATE TABLE public.guide_content_like (
    id integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    auth_user_id uuid NOT NULL,
    content_id integer NOT NULL
);

ALTER TABLE public.guide_content_like ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guide_content_like_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.guide_content_comment (
    id integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    edited_at timestamp(6) with time zone,
    edited_by_user_id uuid,
    deleted_at timestamp(6) with time zone,
    deleted_by_user_id uuid,
    deleted_reason character varying(255),
    auth_user_id uuid NOT NULL,
    content_id integer NOT NULL,
    body character varying(120) NOT NULL
);

ALTER TABLE public.guide_content_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guide_content_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.guide_content_like
    ADD CONSTRAINT guide_content_like_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.guide_content_like
    ADD CONSTRAINT guide_content_like_auth_user_id_content_id_key UNIQUE (auth_user_id, content_id);

ALTER TABLE ONLY public.guide_content_comment
    ADD CONSTRAINT guide_content_comment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.guide_content_like
    ADD CONSTRAINT fk_guide_content_like_user FOREIGN KEY (auth_user_id) REFERENCES public.auth_user(id);

ALTER TABLE ONLY public.guide_content_like
    ADD CONSTRAINT fk_guide_content_like_content FOREIGN KEY (content_id) REFERENCES public.guide_content(id);

ALTER TABLE ONLY public.guide_content_comment
    ADD CONSTRAINT fk_guide_content_comment_user FOREIGN KEY (auth_user_id) REFERENCES public.auth_user(id);

ALTER TABLE ONLY public.guide_content_comment
    ADD CONSTRAINT fk_guide_content_comment_content FOREIGN KEY (content_id) REFERENCES public.guide_content(id);

ALTER TABLE ONLY public.guide_content_comment
    ADD CONSTRAINT fk_guide_content_comment_deleted_by FOREIGN KEY (deleted_by_user_id) REFERENCES public.auth_user(id);

ALTER TABLE ONLY public.guide_content
    ADD CONSTRAINT fk_guide_content_deleted_by FOREIGN KEY (deleted_by_user_id) REFERENCES public.auth_user(id);

ALTER TABLE ONLY public.guide_content_comment
    ADD CONSTRAINT fk_guide_content_comment_edited_by FOREIGN KEY (edited_by_user_id) REFERENCES public.auth_user(id);

CREATE INDEX idx_guide_content_like_content_id ON public.guide_content_like (content_id);
CREATE INDEX idx_guide_content_like_user_id ON public.guide_content_like (auth_user_id);
CREATE INDEX idx_guide_content_comment_content_id ON public.guide_content_comment (content_id);
CREATE INDEX idx_guide_content_comment_deleted_at ON public.guide_content_comment (deleted_at);
